version: '3'
services:
  base: &base
    image: cyberhawk
    working_dir: /home/app/app
    volumes:
      - .:/home/app/app

  base_build:
    <<: *base
    build: .
    command: echo done

  cyberhawk:
    <<: *base
    container_name: cyberhawk
    depends_on: [base_build]
    command: /bin/bash
